<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Macademy\Blog\ViewModel\Post $postVm */
/** @var Magento\Framework\Escaper $escaper */
$postVm = $block->getData('post_vm');
?>

<div class="blog-post-sidebar">
    <!--WRAP TEXT IN ECHO AND WRAP THAT IN __ FUNCTION, PASSED IN AS STRING, MAKES TEXT TRANSLATABLE INTL-->
    <p><strong><?= __('Other Blog Posts') ?></strong></p>
    <ul>
        <?php foreach ($postVm->getList() as $post): ?>
            <li>
                <a href="<?=$block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>">
                    <?= $escaper->escapeHtml($post->getData('title')) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</div>

